version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - data:/data
volumes:
  data: {}
